### ISSUE TITLE
Random spaces or broken characters in html mails with a lot of content

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mime#3]
Hello,

we encountered an issue when sending multipart emails (html and text) with a lot of content.
There either random spaces inside the source code of the mail or broken characters because of invalid character entities.

Since things are working fine when we use the [swiftmailer](https://github.com/swiftmailer/swiftmailer), we could get an idea where the error could be.

According to the [RFC 2045](http://www.faqs.org/rfcs/rfc2045.html) (search for "76"), you are doing a a hard line break instead of a soft line break after 76 characters (see Zend\Mime\Part and search for 76).
Swiftmailer is handling this [76 character limitation](https://github.com/swiftmailer/swiftmailer/search?utf8=%E2%9C%93&q=76&type=) totally differently.
Since this is not an easy topic my thoughts are no having any kind of offense inside. My Intension is to put you into the right direction.

How can you reproduce this issue?
Send a multipart email with a lot of content in html and text.

Best regards,
Stev

[Update]
It would be cool if you could put the link to the [RFC 2045](http://www.faqs.org/rfcs/rfc2045.html) as close to the code as possible.
It took me a while to get the sense behind this "76" number when I had a look into the code.

What about this way?

```php
    'line-length'      => 76, //@link** http://www.faqs.org/rfcs/rfc2045.html
```

Or put the "76" as constant on top and add the link as comment?

---

Originally posted by @stevleibelt at https://github.com/zendframework/zend-mime/issues/29

**Comment by weierophinney** [comment]
Is there a change of getting an update for this ticket?

---

Originally posted by @jobleadsorder at https://github.com/zendframework/zend-mime/issues/29#issuecomment-390948884

**Comment by weierophinney** [comment]
@stevleibelt Could you provide a sample email that demonstrates the issue? This will be easier for us to reproduce if we aren't having to first try and craft an email to trigger the issue.

Thanks!

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-mime/issues/29#issuecomment-390985037

**Comment by weierophinney** [comment]
@weierophinney can I send you a sample of mail that breaks the swift mailer limit? I am having the same problem that I get random breaks in swiftmailer.

Or at least some general instructions on how I could fix that?

---

Originally posted by @Noon2Dusk at https://github.com/zendframework/zend-mime/issues/29#issuecomment-468627172

**Comment by stevleibelt** [comment]
> 
> 
> @stevleibelt Could you provide a sample email that demonstrates the issue? This will be easier for us to reproduce if we aren't having to first try and craft an email to trigger the issue.
> 
> Thanks!
> 
> Originally posted by @weierophinney at [zendframework/zend-mime#29 (comment)](https://github.com/zendframework/zend-mime/issues/29#issuecomment-390985037)

Maybe @tworzenieweb (https://github.com/tworzenieweb) can do this.
It is not part of my job business anymore.

**Comment by sma27** [comment]
We have been experiencing this bug as well using Laminas Mail. Emails with long paragraphs end up with one or more spaces inserted into the content (middle of words, etc.). If we break the paragraph up, the issue goes away. Seems like some hard breaks are being inserted into the message. The messages are stored and then sent from our MySQL database. We've confirmed there are no formatting issues or strange characters in the messages when sent.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [symfony/mime](https://symfony.com/doc/current/components/mime.html)
