### ISSUE TITLE
composer php version need 8.3.2

### ISSUE THREAD

**Issue by linjuchen** [laminas/laminas-mime#38]
I can't install!

**Comment by froschdesign** [comment]
@linjuchen 
This package supports already version 8.3 of PHP. Please see: https://github.com/laminas/laminas-mime/releases/tag/2.12.0

https://github.com/laminas/laminas-mime/blob/08cc544778829b7d68d27a097885bd6e7130135e/composer.json#L24-L27

Check also the documentation of Composer for [explanation of the tilde version range operator](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-).

If you have more questions or problems, please use [our forum or chat](https://getlaminas.org/participate/).
