### ISSUE TITLE
laminas/laminas-mail should be a requirement, not only require-dev

### ISSUE THREAD

**Issue by OskarStark** [laminas/laminas-mime#9]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.7.2

#### Current behavior

```
In Decode.php line 150:

  Attempted to load class "Headers" from namespace "Laminas\Mail".
  Did you forget a "use" statement for "Symfony\Component\Mime\Header\Headers"?
```

`laminas/laminas-mail` should be a dependency of this library

#### How to reproduce

```php
$message = Laminas\Mime\Message::createFromString('foo');
```

#### Expected behavior

No error, because of installed dependency:
![Screenshot 2020-01-27 13 45 52](https://user-images.githubusercontent.com/995707/73175826-571a2b80-410b-11ea-9eea-3c9655f46b18.png)

#### Composer info

![Screenshot 2020-01-27 13 46 51](https://user-images.githubusercontent.com/995707/73175908-829d1600-410b-11ea-972d-dee7e114537e.png)

**Comment by weierophinney** [comment]
Unfortunately, this would create a circular dependency situation. We likely need to move that functionality from the mail package into this one.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you are looking for an actively maintained package alternative, we recommend:
>
> - [symfony/mime](https://symfony.com/doc/current/components/mime.html)
